### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by ainthek** [mattroberts297/jsonwebtokencli#1]
please can you have a loook and update dependecies ?
this is result of npm audit
Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsonwebtokencli                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsonwebtokencli > jsonwebtoken > joi > hoek                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsonwebtokencli                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsonwebtokencli > jsonwebtoken > joi > topo > hoek           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566

**Comment by mattroberts297** [comment]
This should be fixed with 1.5.1 - please reopen if not.
